project:
  type: website

website:
  title: "Seu Nome Completo"
  navbar:
    left:
      - href: index.qmd
        text: Sobre Mim
      - href: pesquisa.qmd
        text: Pesquisas
      - href: cv.pdf
        text: Curr√≠culo (PDF)

format:
  html:
    theme: lux
    toc: true

